name: ip_geolocation
description: A dart package to flutter or dart projects to get your geolocation data from your IP, updated from Darwin Morocho's contribution.
version: 0.0.1
homepage: https://github.com/sebasbose/ip-geolocation


environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.13.3
  meta: ^1.1.8



dev_dependencies:
  flutter_test:
    sdk: flutter
